### ISSUE TITLE
Soundess of Authentication Workflow?

### ISSUE THREAD

**Issue by scottarc** [midorikocak/nanoauth#1]
https://github.com/midorikocak/nanoauth/blob/a90c226d93756a67325e02996ffba56af09276b7/src/Authentication.php#L24-L39

* On line 26, you are creating the hash of an arbitrary password.
* On line 33, you are calling `password_verify()` with the hash you created on line 26, with a password stored in the database.

I believe this means you're storing users' passwords as plaintext? If so, that defeats the purpose of doing `password_hash` and `password_verify`.

**Comment by midorikocak** [comment]
Yes. There is a bug here.  Thanks. Fixing.

**Comment by midorikocak** [comment]
Fixed https://github.com/midorikocak/nanoauth/commit/5e42bb45a436d368737fcbe60f00fc3f3aec0973
